### ISSUE TITLE
Expose kernel_name of nbclient.nbexecute()

### ISSUE THREAD

**Issue by svenkreiss** [executablebooks/jupyter-cache#63]
**Is your feature request related to a problem? Please describe.**

I cannot build jupyterbook without this fix.

**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**

My notebooks contain invalid `kernel_name`s because of editing with VSCode. I want to override the kernel names when executed.

**A clear and concise description of what you want to happen.**

I want jupyterbook to be able to expose a `kernel_name` parameter in addition to the `timeout` parameter.

**A clear and concise description of any alternative solutions or features you've considered.**

I have added myself `kernel_name='python3'` in https://github.com/executablebooks/jupyter-cache/blob/1431ed72961fabc2f09a13553b0aa45f4c8a7c23/jupyter_cache/executors/utils.py#L56 and that fixed it.

Related to https://github.com/executablebooks/jupyter-book/issues/1287

**Comment by chrisjsewell** [comment]
thanks @svenkreiss yes that sounds reasonable 👍 
I'm slowly getting round to looking at improving myst-nb and execution, so will hopefully address this soon

**Comment by svenkreiss** [comment]
Excellent! Thanks for your great work @chrisjsewell .

**Comment by joelostblom** [comment]
Would this work with conda kernels also?

Currently, I create separate conda environments for most projects to facilitate dependency management. `nb_conda_kernels` facilitates this workflow since I only need to install jupyterlab in a single conda env. However, for jupyterbook, I currently need to install it separately in each environment where I want to use it and before each build I need to activate that environment and change the name of the kernel in the notebook to just `python3` instead of e.g. `conda-myenvname-py`. It would be great if jupyterbook could also make use of `nb_conda_kernels` to execute notebook with the specific conda kernel, similarly to how jupyterlab does it (not sure if this is technically feasible).

Related: https://github.com/executablebooks/meta/discussions/222

**Comment by chrisjsewell** [comment]
As noted in https://github.com/executablebooks/jupyter-book/issues/1287, the issue with VS Code is now fixed, in that it now sets standard kernel names like 'python3': microsoft/vscode-jupyter#5732

(this not to say though that there is not still a use case here)

**Comment by chrisjsewell** [comment]
I would this is now closed by: https://github.com/executablebooks/MyST-NB/pull/410
