### ISSUE TITLE
Any reason why sqlalchemy pinned to old version (v1.3.12)?

### ISSUE THREAD

**Issue by psychemedia** [executablebooks/jupyter-cache#65]
Is there any reason why sqlachemy is pinned to an old version (1.3.12)?

**Comment by jaapz** [comment]
As this package is a install requirement of `myst_nb`, currently I'm unable to use `myst_nb` in projects that also require sqlalchemy 1.4+. Pip's new dependency resolver introduced in version 20 is more strict and errors out, because 1.3.12 and 1.4 are not compatible according to pip.

Could you please either change the strictness of this version, or remove the dependency from install_requires alltogether?

**Comment by psychemedia** [comment]
See also: https://github.com/executablebooks/jupyter-cache/pull/64

**Comment by choldgraf** [comment]
Just FYI It looks like the tests are failing on master, so I don't think we can merge #64 until the tests are also passing (not related to #64 I know, but we can't merge a dependency change if the tests are failing). I opened up #69 to track the test failures.
